### ISSUE TITLE
Ktlint breaks with version 0.41.0

### ISSUE THREAD

**Issue by weisJ** [autostyle/autostyle#25]
Using version `0.41.0` of ktlint breaks dependency resolution when running `autstyleApply`.
See https://github.com/JLLeitschuh/ktlint-gradle/issues/458
It is due to 
A possible fix would be to specify
````kotlin
attributes {
    attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling.EXTERNAL))
}
````
when creating configuration for the ktlint dependency.
I think generally it would be great if there was the possibility to let the use configure detached configurations after creation. This way one could implement a temporary fix for themselves.

**Comment by vlsi** [comment]
That is fair. The configuration should be explicit like `autostyleKtlint` rather than a dynamic one.

**Comment by vlsi** [comment]
Fixed in https://github.com/autostyle/autostyle/commit/31788e013a6a7a6b7884e8e7cc765b715744e275
